import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/auth/Navbar";
import Providers from "@/lib/SessionProvider";
import { getSession } from "@/lib/getSession";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  const session = await getSession()
  const user = session?.user 
  return (
    <html lang="en">
      <body className="w-[95%] md:w-[90%] mx-auto">
        <Providers>
        {user && <Navbar user= {user} />}
        {children}
        </Providers>
      </body>
    </html>
  );
}
